version: '3.4'

services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      NODE_PORT: ${NODE_PORT}
    env_file:
      - ./.env
    volumes:
      - ./:/app
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
